config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "homes#top"

  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :books, only: [:create, :index, :show, :edit, :update, :destroy]
  resources :users, only: [:show, :index, :edit, :update]


  get '/home/about' => 'homes#about', as: 'about'
  get '/search', to: 'searches#search'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  has_one_attached :profile_image
  belongs_to :user

  #titleが存在しているかを確認するバリデーション
  validates :title, presence: true
  #bodyが存在しているかを確認するバリデーション
  validates :body, presence: true, length: { maximum: 200 }

  def get_profile_image
    if profile_image.attached?
      profile_image
    else
      'no_image.jpg'
    end
  end

  def self.search_for(content, method)
    content = '' if content.nil?  # contentがnilの場合は空文字列に変更
    if method == 'perfect'
      Book.where(title: content)
    elsif method == 'forward'
      Book.where('title LIKE ?', content+'%')
    elsif method == 'backward'
      Book.where('title LIKE ?', '%'+content)
    else
      Book.where('title LIKE ?', '%'+content+'%')
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy

  has_one_attached :profile_image

  #nameが存在しているかを確認するバリデーション
  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true, presence: true
  validates :introduction, length: { maximum: 50 }
  
  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/sample-author1.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  def self.search_for(content, method)
    if method == 'perfect'
      User.where(name: content)
    elsif method == 'forward'
      User.where('name LIKE ?', content + '%')
    elsif method == 'backward'
      User.where('name LIKE ?', '%' + content)
    else
      User.where('name LIKE ?', '%' + content + '%')
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(resource)
  end


  def after_sign_out_path_for(resource)
    root_path
  end


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end

end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

def create
end

def destroy
end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
  end

  # 以下を追加
  def create
    # １.&2. データを受け取り新規登録するためのインスタンス作成
    @book = Book.new(book_params)
    

    @book.user_id = current_user.id
    # 3. データをデータベースに保存するためのsaveメソッド実行
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      @user = current_user
      render :index
    end
  end





  def index
    @book = Book.new
    @books = Book.all
    @user = current_user
  end

  def show

    @books = Book.all
    @book = Book.new
    @book_show = Book.find(params[:id])
    @user = @book_show.user
  end

  def edit
    # ここから追加
    @book = Book.find(params[:id])
    unless @book.user.id == current_user.id
      redirect_to books_path
    end
    # ここまで追加
  end

  def update
    # ここから追加
    user = User.find(params[:id])
    unless user.id == current_user.id
      redirect_to books_path
    end
    # ここまで追加
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      render :edit
    end  
  end  

  def destroy
    book = Book.find(params[:id])  # データ（レコード）を1件取得
    book.destroy  # データ（レコード）を削除
    redirect_to '/books'  # 投稿一覧画面へリダイレクト 
  end


  private
 # ストロングパラメータ
 def book_params
  params.require(:book).permit(:title, :body)
end


end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:about]

  def top
  end

  def about
    
  end

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :authenticate_user!

	def search
		@model = params[:model]
		@content = params[:content]
		@method = params[:method]
		if @model == 'user'
			@records = User.search_for(@content, @method)
		else
			@records = Book.search_for(@content, @method)
		end
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    @user = current_user
    @book = Book.new
  end
  
  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = @user.books
    @user_show = User.find(params[:id])
  end

  def edit
    # ここから追加
    user = User.find(params[:id])
    unless user.id == current_user.id
      redirect_to user_path(current_user.id)
    end
    # ここまで追加
    @user = User.find(params[:id])
  end

  def update
    # ここから追加
    user = User.find(params[:id])
    unless user.id == current_user.id
      redirect_to users_path
    end
    # ここまで追加
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      render :edit
    end  
  
  end


  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_book.html.erb
<main>
  <div class="container px-5 px-sm-0">
    <div class="row">
      <div class="col-md-3">
        <h2>User info</h2>
          <%= link_to user_path(user.id) do %>
            <%= image_tag user.get_profile_image(100,100) %>
          <% end %>
          <table class="table">
            <tbody>
              <tr></tr>
              <tr>
                <th>name</th>
                <th>mitsu3</th>
              </tr>
              <tr>
                <th>introduction</th>
                <th></th>
              </tr>
            </tbody>
          </table>
          <div class="row">
            <%= link_to edit_user_path(user), class:"btn btn-outline-secondary btn-block" do %>
            <i class="fas fa-user-cog"></i>
            <% end %>
          </div>
          <h2 class="mt-3">New book</h2>
          <%= form_with model: book do |f| %>

          <div class="form-group">
            <div class="field_with_errors">
            
              <h4>Title</h4>
              <%= f.text_field :title %>
            
            </div>
          </div>
          <div class="form-group">
            <div class="field_with_errors">
            
              <h4>Opinion</h4>
              <%= f.text_area :body %>
            
            </div>
          </div>
          <div class="form-group">
            <div class="field_with_errors">
              
                <%= f.submit 'Cleate Book' %>
              
            </div>
          </div>
          <% end %>
        </div>
        <div class="col-md-8 offset-md-1">
          <h2>Books</h2>
          <table class="table table-hover table-inverse">
            <thead>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th colspan="3"></th>
            </tr>
            </thead>
          <tbody>
            <tr>
              <td>
                


              </td>
              <td>



              </td>
              <td>自分への思いやり</td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</main>

app/views/books/_search.html.erb
<% if user_signed_in? %>
  <div class="search_form">
    <%= form_with url: search_path, local: true, method: :get do |f| %>
      <%= f.text_field :word %>
      <%= f.select :range, options_for_select([['User'], ['Book']]) %>
      <%= f.select :search, option_for_select([["完全一致","perfect_match"],["前方一致","forward_match"], ["後方一致","backward_match"],["部分一致","partial_match"]]) %>
      <%= f.submit "検索", class: "btn btn-primary" %>
    <% end %>
  </div>
<% end %>

app/views/books/_sidebar.html.erb
      <div class="col-md-3">
        <h2>User info</h2>
          <%= link_to user_path(user.id) do %>
            <%= image_tag user.get_profile_image(100,100) %>
          <% end %>
          <table class="table">
            <tbody>
              <tr></tr>
              <tr>
                <th>name</th>
                <th><%= user.name %></th>
              </tr>
              <tr>
                <th>introduction</th>
                <th><%= user.introduction %></th>
              </tr>
            </tbody>
          </table>
          <div class="row">
            <%= link_to edit_user_path(user), class:"btn btn-outline-secondary btn-block" do %>
            <i class="fas fa-user-cog"></i>
            <% end %>
          </div>
          <h2 class="mt-3">New book</h2>



          <%= form_with model: book do |f| %>

          <div class="form-group">
            <div class="field_with_errors">
            
              <h4>Title</h4>
              <%= f.text_field :title, class: "form-control book_title", id: "book_title" %>
            
            </div>
          </div>
          <div class="form-group">
            <div class="field_with_errors">
            
              <h4>Opinion</h4>
              <%= f.text_area :body, class: "form-control book_body", id: "book_body" %>
            
            </div>
          </div>
          <div class="form-group">
            <div class="field_with_errors">
              
                <%= f.submit 'Create Book', class:"btn btn-success" %>
              
            </div>
          </div>
          <% end %>
        </div>
        

app/views/books/edit.html.erb
<h1>Books#edit</h1>
<p>Find me in app/views/books/edit.html.erb</p>

<main>
  <p id="notice"></p>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <h1>Editing Book</h1>

        <% if @book.errors.any? %>
          <h3><%= @book.errors.count %>errors prohibited this book from being saved:</h3>
          <ul>
            <% @book.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        <% end %>


         
         
        <%= form_with model: @book do |f| %>

          <label>Title</label><br>
          <%= f.text_field :title, class: "form-control book_title", id: "book_title" %>
          <br>
          <label>Opinion</label><br>
          <%= f.text_area :body, class: "form-control book_body", id: "book_body" %>
          <br>
          <%= f.submit 'Update Book' , class:"btn btn-success" %>

        <% end %>
        </div>
          <%= link_to 'Show', book_path(@book.id) %><%= " | " %>
          <%= link_to 'Back', books_path %>
      </div>
    </div>
  </div>
</main>

app/views/books/index.html.erb
<main>
<% if @book.errors.any? %>
<%= @book.errors.count %> errors prohibited this obj from being saved:
<ul>
  <% @book.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
</ul>
<% end %>
  <div class="container px-5 px-sm-0">
    <div class="row">

      <%= render 'sidebar', books: @books, user: @user , book: @book %>

      <div class="col-md-8 offset-md-1">
        <h2>Books</h2>
          <table class="table table-hover table-inverse">
            <thead>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th colspan="3"></th>
            </tr>
            </thead>
          <tbody>
          <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(book.user.id) do %>
                  <%= image_tag book.user.get_profile_image(100,100) %>
                <% end %>
              </td>
              <td>
                <%= link_to book_path(book.id) do %>
                  <%= book.title %>
                <% end %>
              </td>
              <td>
                <%= book.body %>
              </td>
            </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</main>

app/views/books/search_result.html.erb
<h2>Results index</h2>

<table class="table table-hover table-inverse">
  <!--検索対象モデルがUserの時 -->
  <% if @range == "User" %>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.name %></td>
        </tr>
      <% end %>
    </tbody>
  <% else %>
    <!--検索対象モデルがUserではない時(= 検索対象モデルがBookの時) -->
    <tbody>
      <% @books.each do |book| %>
        <tr>
          <td><%= book.title %></td>
          <td><%= book.body %></td>
        </tr>
      <% end %>
    </tbody>
  <% end %>
</table>

app/views/books/show.html.erb
<main>
  <div class="container px-5 px-sm-0">
    <div class="row">

      <%= render 'sidebar', books: @books, user: @user , book: @book %>

      <div class="col-md-8 offset-md-1">
        <h2>Book detail</h2>
          <table class="table table-hover table-inverse">
            <thead>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th colspan="3"></th>
            </tr>
            </thead>
          <tbody>
            <tr>
              <td>
                <%= link_to user_path(@book_show.user.id) do %>
                  <%= image_tag @book_show.user.get_profile_image(100,100) %>
                  <br>
                  <%= @book_show.user.name %>
                <% end %>
              </td>
              <td>
                <%= link_to book_path(@book_show.id) do %>
                  <%= @book_show.title %>
                <% end %>
              </td>
              <td>
                <%= @book_show.body %>
              </td>
              <td>
              <% if @book_show.user == current_user %>
                <%= link_to "Edit" ,edit_book_path(@book_show.id), class:"btn btn-sm btn-success" %>
              <% end %>
              </td>
              <td>
              <% if @book_show.user == current_user %>
                <%= link_to "Destroy" ,book_path(@book_show.id), class:"btn btn-sm btn-danger", method: :delete, "data-confirm" => "本当に消しますか？" %>
              <% end %>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</main>

app/views/homes/about.html.erb
about
<main>
  <p id="notice"></p>
  <div class="container">
    <div class="row">
      <div class="px-3 mx-auto">
        <h1>
        Welcome to  
        <i class="fa-solid fa-book"></i>
        <strong>Bookers</strong>
         !
        </h1>
      </div>
    </div>
  </div>
</main>

app/views/homes/top.html.erb
top
<main>
  <p id="notice"></p>
  <div class="container">
    <div class="row">
      <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
        <h1>
          Welcome to  
          <i class="fa-solid fa-book"></i>
          <strong>Bookers</strong>
           !!
        </h1>
        <p>
          in 
          <i class="fa-solid fa-book"></i>
          <strong>Bookers</strong>
          , 
        </p>

        <p>you can share and exchange your opinions,inpressions,and emotions <br> about various books!</p>

        <div class="btn-wrapper col-10 mx-auto">
          <div class="row">
            <%= link_to user_session_path, class:"btn btn-info btn-sm btn-block mb-3 sign-in" do %>
              Log in
            <% end %>
          </div>
          <div class="row">
            <%= link_to new_user_registration_path, class:"btn btn-success btn-sm btn-block sign_up" do %>
              Sign up
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/c758cba9a2.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  
  
  
  </head>

  <body>
   <header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
        <%= link_to root_path, class:"nav-link text-light" do %>
          <span>Bookers</span>
        <% end %>
        <button class="navbar-toggler"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse">
          <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
              <li> 
                <%= link_to user_session_path, class:"nav-link text-light" do %>
                  <i class="fas fa-home"></i>
                  Home
                <% end %>
              </li>
              <li>
                <%= link_to user_registration_path, class:"nav-link text-light" do %>
                  <i class="fas fa-users"></i>
                  Users
                <% end %>
              </li>
              <li>
                <%= link_to books_path, class:"nav-link text-light" do %>
                  <i class="fas fa-book-open"></i>
                  Books
                <% end %>
              </li>
              <li>
                <%= link_to destroy_user_session_path, method: :delete, class:"nav-link text-light" do %>
                  <i class="fas fa-sign-out-alt"></i>
                  Log out
                <% end %>
              </li>
            <% else %>
              <li> 
                <%= link_to root_path, class:"nav-link text-light" do %>
                  <i class="fas fa-home"></i>
                  Home
                <% end %>
              </li>
              <li>
                <%= link_to about_path, class:"nav-link text-light" do %>
                  <i class="fas fa-link"></i>
                  About
                <% end %>
              </li>
              <li>
                <%= link_to new_user_registration_path, class:"nav-link text-light" do %>
                  <i class="fas fa-user-plus"></i>
                  Sign up
                <% end %>
              </li>
              <li>
                <%= link_to user_session_path, class:"nav-link text-light" do %>
                  <i class="fas fa-sign-in-alt"></i>
                  Log in
                <% end %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
   </header>
<%= flash[:notice] %>
        <p id="notice"><%= notice %></p>
        <div class="d-flex justify-content-center mb-2">
          <%= render 'searches/form' %>
        </div>
    <%= yield %>

    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Inflatop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/searches/_form.html.erb
<% if user_signed_in? %>
  <%= form_with url: search_path, method: :get, local: true do |f| %>
    <%= f.text_field :content %>
    <%= f.select :model, options_for_select({ "User" => "user", "Book" => "book" }) %>
    <%= f.select :method, options_for_select({ "完全一致" => "perfect", "前方一致" => "forward", "後方一致" => "backward", "部分一致" => "partial" }) %>
    <%= f.submit '検索' %>
  <% end %>
<% end %>

app/views/searches/search.html.erb
<% if @model == 'user' %>
	<h3>Users search for "<%= @content %>"</h3>
  <%= render 'users/index', users: @records %>
<% elsif @model == 'book' %>
	<h3>Books search for "<%= @content %>"</h3>
  <%= render 'books/index', books: @records %>
<% end %>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>


<main>
  <p id="notice"></p>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <h2>User info</h2>

        <% if @user.errors.any? %>
          <h3><%= @user.errors.count %>errors prohibited this obj from being saved:</h3>
          <ul>
            <% @user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        <% end %>

        <%= form_with model: @user do |f| %>

          <label>Name</label><br>
          <%= f.text_field :name, class: "form-control user_name", id: "user_name" %>
          <br>
          <label for="inputImage">Image</label><br>
          <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %> <br> 
          <label>Introduction</label><br>
          <%= f.text_area :introduction, class: "form-control user_introduction", id: "user_introduction" %>
          <br>
          <%= f.submit 'Update User' , class:"btn btn-secondary" %>

        <% end %>

          
      </div>
    </div>
  </div>
</main>

app/views/users/index.html.erb
<!-- ユーザーの一覧 -->

<main>
  <div class="container px-5 px-sm-0">
    <div class="row">

      <div class="col-md-3">
      <h2>User info</h2>
        <%= link_to user_path(@user.id) do %>
          <%= image_tag @user.get_profile_image(100,100) %>
        <% end %>
        <table class="table">
          <tbody>
            <tr></tr>
            <tr>
              <th>name</th>
              <th><%= @user.name %></th>
            </tr>
            <tr>
              <th>introduction</th>
              <th><%= @user.introduction %></th>
            </tr>
          </tbody>
        </table>
        <div class="row">
          <%= link_to edit_user_path(@user), class:"btn btn-outline-secondary btn-block" do %>
          <i class="fas fa-user-cog"></i>
          <% end %>
        </div>
        <h2 class="mt-3">New book</h2>
        <%= form_with model: @book do |f| %>

        <div class="form-group">
          <div class="field_with_errors">
          
            <h4>Title</h4>
            <%= f.text_field :title %>
          
          </div>
        </div>
        <div class="form-group">
          <div class="field_with_errors">
          
            <h4>Opinion</h4>
            <%= f.text_area :body %>
          
          </div>
        </div>
        <div class="form-group">
          <div class="field_with_errors">
            
              <%= f.submit 'Create Book', class:"btn btn-success" %>
            
          </div>
        </div>
        <% end %>
      </div>



      <div class="col-md-8 offset-md-1">
        <h2>Users</h2>
          <table class="table">
            <thead>
              <th></th>
              <th>image</th>
              <th>name</th>
              <th colspan="3"></th>
            </tr>
            </thead>
            <tbody>
            <% @users.each do |user| %>
              <tr>
                <td>
                  <%= image_tag user.get_profile_image(100,100) %>
                </td>
                <td>
                  <%= user.name %>
                </td>
                <td>
                  <%= link_to user_path(user.id) do %>
                  Show
                  <% end %>
                </td>
              </tr>
            <% end %>
            </tbody>
        </table>
      </div>
    </div>
  </div>
</main>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>


<main>
  <div class="container px-5 px-sm-0">
    <div class="row">

      <%= render '/books/sidebar', books: @books, user: @user , book: @book %>

      <div class="col-md-8 offset-md-1">
        <h2>Books</h2>
          <table class="table table-hover table-inverse">
            <thead>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th colspan="3"></th>
            </tr>
            </thead>
          <tbody>
            <% @user_show.books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(@user_show.id) do %>
                  <%= image_tag @user_show.get_profile_image(100,100) %>
                  <br>
                  <%= @user_show.name %>
                <% end %>
              </td>
              <td>
                <%= link_to book_path(book.id) do %>
                  <%= book.title %>
                <% end %>
              </td>
              <td>
                <%= book.body %>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</main>